import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>React Conf</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <p className='text-red-500 font-bold text-lg'>Hello world</p>
    </div>
  )
}
